---
- name: Add Chris Lea's NodeJS repository
  apt_repository: >
    repo=ppa:chris-lea/node.js

- name: apt-get update and install NodeJS
  apt: >
    pkg=nodejs
    state=present
    update_cache=true
